[preferences.ScottishTaxBenefitModel]

public-artifact_server_upload = "vw@virtual-worlds.biz:public_html/artifacts/"
public-artifact_server_url = "https://virtual-worlds.biz/artifacts/"
local-artifact_server_upload = "stb-artifacts:"
local-artifact_server_url = "http://stb-artifacts/"

auto_weight = true
default_run_name = "default_run"
use_weighting = true
target_nation = "N_Scotland"
dump_frames = false
prices_file="indexes.tab"
to_y = 2024
to_q = 3
means_tested_routing = "modelled_phase_in"
poverty_line_source = "pl_first_sys"
ineq_income_measure = "eq_bhc_net_income"
do_marginal_rates = false
do_replacement_rates = false
replacement_rate_hours = 30
mr_rr_upper_age = 68
target_bc_income = "ahc_hh"
target_mr_rr_income = "ahc_hh"
mr_incr = 0.001
requested_threads = 1
impute_employer_pension = true
benefit_generosity_estimates_available = true
weight_type = "constrained_chi_square"
lower_multiple = 0.20 # these values can be narrowed somewhat, to around 0.25-4.7
upper_multiple = 5.0
do_health_estimates = false 
sf12_depression_limit = 45.60
create_own_grossing = true
use_average_band_d = false
indirect_method = "matching"
impute_fields_from_consumption = true
indirect_matching_dataframe = "lcf-frs-scotland-only-matches-2015-2021"
expenditure_dataset = "lcf_subset-2018-2020"
wealth_method = "no_method"
wealth_matching_dataframe = "was-wave-7-frs-scotland-only-matches-2015-2021-w3"
wealth_dataset = "was_wave_7_subset"
do_indirect_tax_calculations = false
do_legal_aid = true
legal_aid_probs_data = "civil-legal-aid-probs-scotland-2015-2012"
export_full_results = false
do_dodgy_takeup_corrections = false
data_source = "FRSSource"
skiplist = ""

