name = "ScottishTaxBenefitModel"
uuid = "a734f2ee-4b7f-478f-84ca-797081d39f6e"
authors = ["Graham Stark"]
version = "0.1.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BudgetConstraints = "51aacf4b-43e8-45f9-b960-ce5126c2a956"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HttpCommon = "77172c1b-203f-54ac-aa54-3f1198fe9f90"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MarkdownTables = "1862ce21-31c7-451e-824c-f20fa3f90fa2"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PovertyAndInequalityMeasures = "582645c0-90fa-497a-98b9-936b80116c29"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RegressionTables = "d519eb52-b820-54da-95a6-98e1306fdade"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SurveyDataWeighting = "0d23d9a6-c44e-4ca5-9c36-ffcb6594a9c5"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ArgCheck = "2.3.0, 4"
BenchmarkTools = "1.3.2, 4"
BudgetConstraints = "1.0.1, 3"
CSV = "0.10.10, 1"
ChunkSplitters = "2"
Colors = "0.12.10, 1"
DataFrames = "1.3.6, 2"
Documenter = "1"
Format = "1"
FromFile = "0.1.5, 1"
GLM = "1.8.3, 3"
HttpCommon = "0.5.0, 1"
Infiltrator = "1.6.3, 3"
IterableTables = "1.0.0, 3"
IteratorInterfaceExtensions = "1.0.0, 3"
JLD2 = "0.4.31, 1"
JSON3 = "1.12.0, 3"
LoggingExtras = "1.0.0, 3"
MarkdownTables = "1.1.0, 3"
Observables = "0.5.4, 1"
OrderedCollections = "1"
Parameters = "0.12.3, 1"
PovertyAndInequalityMeasures = "1.0.10,2"
PrettyTables = "1.3.1, 2"
Reexport = "1.2.2, 2"
RegressionTables = "0.7"
Roots = "2.0.14, 3"
StatFiles = "0.8.0, 1"
StaticArrays = "1.5.24, 2"
Statistics = "1.9.0, 2"
StatsBase = "0.34.3, 1"
StatsModels = "0.6, 0.7, 1"
StructTypes = "1.10.0, 2"
SurveyDataWeighting = "1.0.4, 2"
TableTraits = "1.0.1, 2"
Tables = "1.10.1, 2"
TimeSeries = "0.23.1, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
