name = "ScottishTaxBenefitModel"
uuid = "a734f2ee-4b7f-478f-84ca-797081d39f6e"
authors = ["Graham Stark"]
version = "0.1.5"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArtifactUtils = "8b73e784-e7d8-4ea5-973d-377fed4e3bce"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BudgetConstraints = "51aacf4b-43e8-45f9-b960-ce5126c2a956"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataScienceTraits = "6cb2f572-2d2b-4ba6-bdb3-e710fa044d6c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HttpCommon = "77172c1b-203f-54ac-aa54-3f1198fe9f90"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MarkdownTables = "1862ce21-31c7-451e-824c-f20fa3f90fa2"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
ModelParameters = "4744a3fa-6c31-4707-899e-a3298e4618ad"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PovertyAndInequalityMeasures = "582645c0-90fa-497a-98b9-936b80116c29"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RegressionTables = "d519eb52-b820-54da-95a6-98e1306fdade"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SummaryTables = "6ce4ecf0-73a7-4ce3-9fb4-80ebfe887b60"
SurveyDataWeighting = "0d23d9a6-c44e-4ca5-9c36-ffcb6594a9c5"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ArgCheck = "2, 3, 4"
ArtifactUtils = "0.2, 0.3, 1"
Artifacts = "1"
BenchmarkTools = "1, 4"
BudgetConstraints = "1, 3"
CSV = "0.10, 0.11, 0.12, 0.2, 1"
ChunkSplitters = "2"
Colors = "0.12, 0.13, 0.14, 0.2, 1"
DataFrames = "1, 2"
DataScienceTraits = "1.0.1"
Documenter = "1"
Format = "1"
FromFile = "0.1, 0.2, 1"
GLM = "1, 3"
HttpCommon = "0.5.0, 1"
Infiltrator = "1, 3"
IterableTables = "1, 3"
IteratorInterfaceExtensions = "1, 2, 3"
JLD2 = "0.4, 0.5, 1"
JSON3 = "1, 2, 3"
LazyArtifacts = "1"
LinearAlgebra = "1"
LoggingExtras = "1, 2, 3"
MarkdownTables = "1, 2, 3"
ModelParameters = "0.4, 0.5, 1"
Observables = "0.5, 0.6, 1"
Parameters = "0.12, 0.13, 0.2, 1"
Pkg = "1"
PovertyAndInequalityMeasures = "1,2"
Preferences = "1, 2"
PrettyTables = "1, 2"
ProgressLogging = "0.1, 0.2, 1"
Reexport = "1, 2"
RegressionTables = "0.7"
Roots = "2, 3"
StatFiles = "0.8.0, 1"
StaticArrays = "1, 2"
Statistics = "1, 2"
StatsBase = "0.1, 0.34, 0.35, 0.36, 0.4, 1"
StatsModels = "0.6, 0.7, 1"
StructTypes = "1, 2"
SummaryTables = "3, 4"
SurveyDataWeighting = "1, 2"
TableTraits = "1, 2"
Tables = "1, 2"
TimeSeries = "0.23, 0.24, 0.25, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[preferences.ScottishTaxBenefitModel]
ccode = ""
default_run_name = "default_run"
do_legal_aid = false
do_local_run = false
do_marginal_rates = false
do_replacement_rates = false
dump_frames = false
dump_frames2 = true
ineq_income_measure = "eq_bhc_net_income"
local-artifact_server_upload = "stb-artifacts:/var/www/stb-artifacts/"
local-artifact_server_url = "http://stb-artifacts/"
means_tested_routing = "modelled_phase_in"
poverty_line_source = "pl_first_sys"
prem2 = "enhanced_disability_child"
public-artifact_server_upload = "vw@virtual-worlds.biz:public_html/artifacts/"
public-artifact_server_url = "https://virtual-worlds.biz/artifacts/"
replacement_rate_hours = 30
target_nation = "N_Scotland"
to_q = 4
to_y = 2024
weighting_strategy = "use_precomputed_weights"

[targets]
test = ["Test"]
